# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\openpose\test_1\ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 644)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(510, 230, 321, 151))
        self.widget.setObjectName("widget")
        self.account = QtWidgets.QLineEdit(self.widget)
        self.account.setGeometry(QtCore.QRect(30, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.account.setFont(font)
        self.account.setStyleSheet("border:2px solid ;\n"
"gridline-color: rgb(88, 152, 255);\n"
"\n"
"border-radius:8px;\n"
"background-color: rgb(213, 213, 213);")
        self.account.setText("")
        self.account.setReadOnly(False)
        self.account.setObjectName("account")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 80, 251, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:2px solid ;\n"
"gridline-color: rgb(88, 152, 255);\n"
"\n"
"border-radius:8px;\n"
"background-color: rgb(213, 213, 213);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 380, 141, 171))
        self.label_3.setStyleSheet("border-image: url(:/pic/c96cf2a7c6eb2abd7953f826a526a9a.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 60, 351, 491))
        self.label_4.setStyleSheet("border-image: url(:/pic/71405261d7aa8194755c61833dbac02.png);\n"
"border-top-left-radius:40px;\n"
"border-bottom-left-radius:40px;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(585, 101, 211, 91))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(37)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(834, 78, 30, 30))
        self.pushButton_2.setStyleSheet("\n"
"#pushButton_2 {\n"
"    border: none;\n"
"}\n"
"\n"
"#pushButton_2:hover {\n"
"    background-color: rgb(235, 235, 235); /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(576, 407, 181, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(212, 38, 255);\n"
"    gridline-color: rgb(255, 249, 235);\n"
"    border-radius: 8px;\n"
"    border:2px solid;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d5d5d5;/* 设置按钮被点击时的背景颜色 */\n"
"padding:2px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a7a7a7; /* 设置按钮被点击时的背景颜色 */\n"
"}\n"
"")
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 390, 141, 171))
        self.label_2.setStyleSheet("border-image: url(:/pic/77a4d73ccff048e4b26632a1bc0e8c0.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(451, 60, 441, 491))
        self.label_5.setStyleSheet("background-color: rgb(213, 213, 213);\n"
"border-top-right-radius:40px;\n"
"border-bottom-right-radius:40px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(580, 380, 181, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 35, 39);")
        self.label_6.setObjectName("label_6")
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.widget.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.account.setPlaceholderText(_translate("MainWindow", "请输入账号"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.label_6.setText(_translate("MainWindow", "用户名或者密码有错误！"))
from mp.source.image import pic_rc
