# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\openpose\test_1\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1481, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 10, 1051, 671))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1051, 71))
        self.frame_2.setStyleSheet("background-color: rgb(185, 185, 185);\n"
"border-top-left-radius:30px;\n"
"border-top-right-radius:30px;\n"
"border-bottom:2px solid")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(11, 0, 281, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(1000, 20, 28, 28))
        self.pushButton.setStyleSheet("#pushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"#pushButton {\n"
"\n"
"    background-color: rgb(185, 185, 185);\n"
"}\n"
"#pushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(232, 232, 232);\n"
"}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(280, 20, 321, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:none;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 70, 171, 601))
        self.frame_3.setStyleSheet("background-color: rgb(185, 185, 185);\n"
"\n"
"border-bottom-left-radius:30px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 16, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(212, 38, 255);\n"
"    gridline-color: rgb(255, 249, 235);\n"
"    border-radius: 8px;\n"
"    border:2px solid;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d5d5d5;/* 设置按钮被点击时的背景颜色 */\n"
"padding:2px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a7a7a7; /* 设置按钮被点击时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 163, 98, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(212, 38, 255);\n"
"    gridline-color: rgb(255, 249, 235);\n"
"    border-radius: 8px;\n"
"    border:2px solid;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d5d5d5;/* 设置按钮被点击时的背景颜色 */\n"
"padding:2px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a7a7a7; /* 设置按钮被点击时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 113, 98, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(212, 38, 255);\n"
"    gridline-color: rgb(255, 249, 235);\n"
"    border-radius: 8px;\n"
"    border:2px solid;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d5d5d5;/* 设置按钮被点击时的背景颜色 */\n"
"padding:2px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a7a7a7; /* 设置按钮被点击时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(120, 163, 33, 33))
        self.label_6.setStyleSheet("image: url(:/pic/play.svg);")
        self.label_6.setText("")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setEnabled(True)
        self.label_13.setGeometry(QtCore.QRect(121, 158, 31, 41))
        self.label_13.setStyleSheet("image: url(:/pic/pause.svg);\n"
"")
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 330, 151, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border:1px solid black;\n"
"")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(27, 299, 51, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(121, 107, 31, 41))
        self.label_14.setStyleSheet("image: url(:/pic/pause.svg);\n"
"")
        self.label_14.setText("")
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(120, 112, 33, 33))
        self.label_9.setStyleSheet("image: url(:/pic/play.svg);")
        self.label_9.setText("")
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox.setGeometry(QtCore.QRect(36, 360, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("")
        self.checkBox.setIconSize(QtCore.QSize(20, 20))
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_2.setGeometry(QtCore.QRect(36, 392, 101, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("")
        self.checkBox_2.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setGeometry(QtCore.QRect(20, 465, 112, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_2.setGeometry(QtCore.QRect(94, 466, 61, 19))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_3.setGeometry(QtCore.QRect(37, 424, 111, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("")
        self.checkBox_3.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 216, 98, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(212, 38, 255);\n"
"    gridline-color: rgb(255, 249, 235);\n"
"    border-radius: 8px;\n"
"    border:2px solid;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d5d5d5;/* 设置按钮被点击时的背景颜色 */\n"
"padding:2px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a7a7a7; /* 设置按钮被点击时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 61, 131, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(212, 38, 255);\n"
"    gridline-color: rgb(255, 249, 235);\n"
"    border-radius: 8px;\n"
"    border:2px solid;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d5d5d5;/* 设置按钮被点击时的背景颜色 */\n"
"padding:2px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a7a7a7; /* 设置按钮被点击时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 263, 98, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(212, 38, 255);\n"
"    gridline-color: rgb(255, 249, 235);\n"
"    border-radius: 8px;\n"
"    border:2px solid;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color:#d5d5d5;/* 设置按钮被点击时的背景颜色 */\n"
"padding:2px;\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a7a7a7; /* 设置按钮被点击时的背景颜色 */\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(172, 70, 441, 381))
        self.frame_4.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"border-right:1px solid;\n"
"border-bottom:1px solid")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider.setGeometry(QtCore.QRect(19, 359, 421, 22))
        self.horizontalSlider.setStyleSheet("      QSlider::groove:horizontal {\n"
"            border: none;\n"
"            height: 2px;\n"
"            background-color: lightgray;\n"
"        }\n"
"\n"
"        QSlider::handle:horizontal {\n"
"            background-color: #f1964c;\n"
"            width: 16px;\n"
"            margin: -8px 0px -8px 0px;\n"
"            border-radius: 8px;\n"
"\n"
"        }\n"
"\n"
"        QSlider::sub-page:horizontal {\n"
"            background-color: #f1964c;\n"
"        }\n"
"\n"
"")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 441, 351))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(113, 113, 113);")
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(613, 70, 440, 381))
        self.frame_6.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"\n"
"border-bottom:1px solid")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 441, 351))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;\n"
"color: rgb(113, 113, 113);\n"
"background-color: rgb(0, 0, 0);")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(162, 449, 891, 221))
        self.frame_5.setStyleSheet("#frame_5 {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#frame_5 {\n"
"    border-bottom-right-radius: 30px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.progressBar_2 = QtWidgets.QProgressBar(self.frame_5)
        self.progressBar_2.setGeometry(QtCore.QRect(130, 10, 621, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setStyleSheet("      QProgressBar {\n"
"            border: 2px solid #b9b9b9;\n"
"            background-color: white;\n"
"            padding-left: 2px;\n"
"            padding-right: 2px;\n"
"          \n"
"\n"
"        }\n"
"\n"
"        QProgressBar::chunk {\n"
"            background-color: #b9b9b9;\n"
"            margin-top: 2px;\n"
"            margin-bottom: 2px;\n"
"        }\n"
"  border-top-left-radius:30px;")
        self.progressBar_2.setProperty("value", 50)
        self.progressBar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser.setGeometry(QtCore.QRect(80, 60, 731, 141))
        self.textBrowser.setStyleSheet("border:1px solid #aaaaaa;\n"
"\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(30, 40, 81, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_5.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_10.clicked.connect(self.textBrowser.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "武术动作自动评分系统"))
        self.pushButton_6.setText(_translate("MainWindow", "加载视频"))
        self.pushButton_8.setText(_translate("MainWindow", "预览"))
        self.pushButton_5.setText(_translate("MainWindow", "开始"))
        self.label_8.setText(_translate("MainWindow", "设置"))
        self.checkBox.setText(_translate("MainWindow", "保存日志"))
        self.checkBox_2.setText(_translate("MainWindow", "保存图片"))
        self.radioButton.setText(_translate("MainWindow", "模型1"))
        self.radioButton_2.setText(_translate("MainWindow", "模型2"))
        self.checkBox_3.setText(_translate("MainWindow", "骨架可视化"))
        self.pushButton_9.setText(_translate("MainWindow", "展示最佳帧"))
        self.pushButton_7.setText(_translate("MainWindow", "加载规则"))
        self.pushButton_10.setText(_translate("MainWindow", "清空输出"))
        self.label_3.setText(_translate("MainWindow", "输入视频显示"))
        self.label_4.setText(_translate("MainWindow", "输出视频显示"))
        self.label_5.setText(_translate("MainWindow", "输出"))
from mp.source.image import pic_rc
